### ISSUE TITLE
Add Optional --notes parameter to promote subcommand

### ISSUE THREAD

**Issue by TraGicCode** [akamai/cli-promotional-deployment#1]
Instead of putting 'Akamai PD Activation' it would be awesome to have an optional parameter to allow for the user to put their own custom notes.  This would allow a CI/CD server to put something such as:

1. The Commit message.
2. The SHA of the commit.

**Comment by jumenzel** [comment]
That should be easy to add. Thank you for the feedback.

**Comment by jnchin-james** [comment]
Yes, you can do the promote command with a -m option with a message:

 Usage: promote|pm [options] [targetEnvironment]

  Promote (activate) an environment. This command also executes the merge and save commands mentioned above by default.

  Options:

    -p, --pipeline [pipelineName]  pipeline name
    -n, --network <network>        Network, either 'production' or 'staging', can be abbreviated to 'p' or 's'
    -e, --emails [emails]          Comma separated list of email addresses. Optional if default emails were previously set with set-default
    -m, --message [message]        Promotion message passed to activation backend
    -w, --wait-for-activate        Return after promotion of an environment is active.
    --force                        Force promotion if previous environment aren't promoted or even saved.
    -h, --help                     output usage information

**Comment by TraGicCode** [comment]
This is great stuff.  Thanks
