### ISSUE TITLE
Add argument to change output type for commands that output tables

### ISSUE THREAD

**Issue by TraGicCode** [akamai/cli-promotional-deployment#3]
When attempting to automate promotion it would be nice to be able pas some argument to make the output come back as json instead of an ASCII table.  Without this it's really hard to exctract certain things like activationid etc...

**Comment by jumenzel** [comment]
Yes, agreed. We should add that soon.

**Comment by jnchin-james** [comment]
Added the ability to use -f to choose between json or table format!

    -f, --format [format]                              Select output format, allowed values are 'json' or 'table'
