### ISSUE TITLE
Changing edgehost name causes PD to fail

### ISSUE THREAD

**Issue by akshayranganath** [akamai/cli-promotional-deployment#7]
When I was building a new pipeline, I updated the _hostnames.json_. My change was to re-use an existing edge host name.

After making the change, I was unable to run either the `save` or `promote` commands. After looking at the debug messages, here's what I think is the problem.

When a change is made to the edge hostname, the host information needs to be updated. For this purpose, _pd_ makes a call to the PAPI API end point `PUT /papi/v0/properties/<<config-id>>/versions/1/hostnames`. This call fails with the message saying required parameter `contractId` is missing. The documentation says that this is optional but, it looks like this is wrong. Here's the exact error message.

```javascript
{ server: 'Apache-Coyote/1.1',
     'content-language': 'en',
     vary: 'Accept-Encoding',
     'content-type': 'application/problem+json;charset=UTF-8',
     'content-length': '374',
     date: 'Wed, 08 Aug 2018 18:27:31 GMT',
     connection: 'close' },
  statusCode: 400,
  body: '{\n  "type" : "https://problems.luna.akamaiapis.net/papi/v0/missing-required-parameter",\n  "title" : "Missing required parameter",\n  "status" : 400,\n  "detail" : "Missing required parameter `contractId`.",\n  "instance" : "https://akab-uulemrmaiat7xtl6-ipfwzox4cdhka7ux.luna.akamaiapis.net/papi/v0/properties/<<config-id>>/versions/1/hostnames#a7f103ec-ed43-4a15-ac61-39324ba37075"\n}' }
[2018-08-08T11:27:31.301] [ERROR] devops-prov.openclient - request failure, status code: '400', response body:  {
  "type" : "https://problems.luna.akamaiapis.net/papi/v0/missing-required-parameter",
  "title" : "Missing required parameter",
  "status" : 400,
  "detail" : "Missing required parameter `contractId`.",
  "instance" : "https://akab-uulemrmaiat7xtl6-ipfwzox4cdhka7ux.luna.akamaiapis.net/papi/v0/properties/478906/versions/1/hostnames#a7f103ec-ed43-4a15-ac61-39324ba37075"
}
```

Could you please update the pd code to ensure that includes the contractId parameter when making the call?

**Comment by jnchin-james** [comment]
this issue should be resolved
