### ISSUE TITLE
Fallback mechanism for Property Manager installation

### ISSUE THREAD

**Issue by saratrajan** [akamai/cli-promotional-deployment#78]
I am creating this issue as per Akamai Tech Support. There was an issue a few week's back when the command <akamai install property-manager> was failing continuously for almost a day (09/23 to be precise) due to NPM error, within ADO pipelines, as follows:

```json
unable to install package manager: npm
ERROR[0018] unable to execute package manager: npm command=install
ERROR[0018] INSTALL error: Unable to install selected package command=install
```
I am using the recommended way of `brew install akamai` before installing the Property Manager. So we are not sure if Brew was facing any regressions that given day, as well!

I would like to understand if there is any fallback mechanism with which one could install Property Manager and all similar packages of Akamai (_like Onboard, CPS, Cloudlets_) from command line just in case <akamai install> command fails.

Thank you for response, in advance.

**Comment by dstopka** [comment]
Hi @saratrajan!

If `install` command keeps failing by any reason, I can suggest looking into using akamai docker images (more information can be found here - [akamai-docker](https://github.com/akamai/akamai-docker)).

If using docker is not an option you can try installing the necessary package manually. For cli-property-manager you'd need to do
```
git clone --depth 1 https://github.com/akamai/cli-property-manager.git
cd cli-property-manager
npm install --production
cp -r . ~/.akamai-cli/src/cli-property-manager 
```

I hope this answers your question, if not please let me know.

Regards,
Darek

**Comment by saratrajan** [comment]
Thank you for providing a workaround here. Closing this issue.

Regards,
Sarat
