### ISSUE TITLE
error keeps showing even if net storage is removed

### ISSUE THREAD

**Issue by tpimenta88** [akamai/cli-promotional-deployment#82]
{
        "type": "https://problems.luna.akamaiapis.net/papi/v0/validation/generic_behavior_issue.netstorage_group_not_available",
        "errorLocation": {
            "template": "templates/Maintenance_page_origins.json",
            "variables": [
                "environments/dev/variables.json"
            ],
            "location": "children/0/behaviors/0/options/netStorage",
            "value": {
                "downloadDomainName": "sitemaps.download.akamai.com",
                "cpCode":1111,
                "g2oToken": null
            }
        },
        "detail": "`Origin Server`: The NetStorage Account (<strong>sitemaps.download.akamai.com</strong>) cannot be used with this property because the NetStorage Account is not associated with this property's group. Please contact your Account Administrator to resolve this."
    }
]'

**Comment by Slonimskaia** [comment]
Hi @tpimenta88,

Could you provide more information? Please include terraform configuration file to better understand your issue and steps to reproduce it. After that we will try our best to help you.

Best regards,
Tatiana Slonimskaia

**Comment by tpimenta88** [comment]
not using terraform.
using command line - Akamai CLI

**Comment by Slonimskaia** [comment]
@tpimenta88 thank you for bringing this issue to our attention. I will try to reproduce it and contact you if I need more information.

**Comment by mimazaka** [comment]
Hello @tpimenta88,

Could you please provide more details which action you tried to perform using cli-property-manager? 

Please describe steps you have performed, in order to receive error which you reported? It will help us to resolve this issue.

Regards,
Michał

**Comment by tpimenta88** [comment]
Hi,
so after opening case with Akamai support, regarding this they found that the Netstorage cpcode in question was created erroneously.
It worked with the Akamai portal but when used via API, permissions were missing hence the error.
They didn't elaborate on which permission but made the change so CLI no longer complains on cpcode.
It now complains/error on the following issue also reported titled :

DXE-2447 command >> update-local | incomplete , possible missing arguments

**Comment by Slonimskaia** [comment]
Hi @tpimenta88,

Could this issue be closed?

Best regards,
Tatiana Slonimskaia

**Comment by tpimenta88** [comment]
Hi Tatiana,
Thanks for your contact.

Yes, you can close for now. We are trying to make other tests and trying to find another solution.

Thanks for your help.
Regards
________________________________
